- id: cp
  name: cp
  description: Copies files
  path: cp
  runtime: other

  parameters:
    - id: no_overwrite
      name: No overwrite
      description: Do not overwrite existing file
      type: argument
      cardinality: 1..1
      label: -n
      data_type: boolean
      default: true

    - id: input_file
      name: Input file name
      description: Input file name
      type: input
      cardinality: 1..1
      data_type: file

    - id: output_file
      name: Output file name
      description: Output file name
      type: output
      cardinality: 1..1
      data_type: file

- id: sleep
  name: sleep
  description: sleeps for the given amount of seconds
  path: sleep
  runtime: other

  parameters:
    - id: seconds
      name: seconds to sleep
      description: The number of seconds to sleep
      type: argument
      cardinality: 1..1
      data_type: integer

- id: docker_hello_world
  name: Docker hello world
  description: Runs the hello-world Docker image
  path: hello-world
  runtime: docker
  parameters: []
